### ISSUE TITLE
[Feature request] OweWire bus support

### ISSUE THREAD

**Issue by amid0** [cesanta/mongoose-os#117]
Hello.
I wounder is the any plans to support Dallas OneWire bus in Smart JS?
There are many useful sensors and IC's with one wire bus.
Also this bus called iButton bus.
First of all for me interesting popular temperature sensor DS18B20. By the way NodeMCU adaptation for esp8266 already support this sensor )).
Here is few links:
https://en.wikipedia.org/wiki/1-Wire
https://www.maximintegrated.com/en/app-notes/index.mvp/id/1796
https://datasheets.maximintegrated.com/en/ds/DS18B20.pdf
https://www.adafruit.com/datasheets/DS18B20.pdf
https://vaasa.hacklab.fi/2015/01/12/esp8266-ds18b20-thingspeak-nodemcu/

Thank you in advance.

**Comment by alashkin** [comment]
This is a feature request, so could you give me more background on why do you need that? What is the project, and how that functionality will be used?

**Comment by lukevenediger** [comment]
+1 - I have a need to integrate with a DS18B20 temperature sensor and this would make it a whole lot easier.

**Comment by dvv** [comment]
+1 for the same reason. TIA

**Comment by codelinq** [comment]
+1 for the same reason. Since there are c libraries written for onewire and ds18b20, would it be possible to include the OneWire.h file and write js wrapper using mjs's ffi to call the c functions? Or is that just wishful thinking? Here is the arduino OneWire library. https://github.com/PaulStoffregen/OneWire/blob/master/OneWire.cpp

**Comment by meteofelix** [comment]
+1 also for being able to use the DS18B20

**Comment by El-Mango** [comment]
+1 also for being able to use the DS18B20

**Comment by cristiancs** [comment]
Any news on this?

**Comment by cpq** [comment]
The PR is in the review, expect a commit tomorrow.

**Comment by cpq** [comment]
https://github.com/cesanta/mongoose-os/tree/master/fw/examples/c_arduino_onewire
