### ISSUE TITLE
GPIO.setISR() allows only one invocation per pin?

### ISSUE THREAD

**Issue by carterw** [cesanta/mongoose-os#147]
I'm experimenting with GPIO.setISR() and finding that I can call it one time to set a transition mode and a function callback for a pin. But if I try to call it again on that pin I get an error;
"Only one interruption handler is allowed for pin"

Is this by design or am I doing something wrong? It seems like I should be able to turn it off or set it to something different.

GPIO.setISR(0, GPIO.ANYEDGE, function() {
            print('pin ' + pin + ' transitioned');
        });  // succeeds

GPIO.setISR(0, GPIO.OFF, function() {});  // fails!

**Comment by carterw** [comment]
Another odd thing. If I set;
GPIO.setISR(0, GPIO.LOW, function() {
print('pin ' + pin + ' transitioned');
}); // succeeds

and then later...
GPIO.write(0, false);

**Comment by cpq** [comment]
The GPIO API has changed:
https://github.com/cesanta/mongoose-os/blob/master/fw/examples/mjs_hello/fs/api_gpio.js

Now, it is an FFI-ed C API.
See https://mongoose-iot.com/blog/mjs-a-new-approach-to-embedded-scripting/ for more info and rationale of FFI.

Please reopen if needed.
