### ISSUE TITLE
stm32 can't flash

### ISSUE THREAD

**Issue by MobiusHorizons** [cesanta/mongoose-os#179]
`mgos` seems to be concatenating the port name and the file it is attempting to write, leading to the following error:

```
Loaded c_hello/stm32 version 1.0 (20170104-042207/???)
Copying c_hello.bin to /dev/tty.wchusbserial1420...
Error: open /dev/tty.wchusbserial1420/c_hello.bin: not a directory
```

**Comment by cpq** [comment]
@rojer please take a look

**Comment by MobiusHorizons** [comment]
is the source for the `mgos` tool somewhere public? if so, I could take a look for the error myself.

**Comment by cpq** [comment]
Are you trying to flash STM32 board?

**Comment by MobiusHorizons** [comment]
Yes, I build the `c_hello` project for `arch stm32`, and I was trying to flash to the serial bootloader.

**Comment by cpq** [comment]
Got it, thank you @MobiusHorizons !
STM32 is not yet functional, work in progress!

**Comment by cpq** [comment]
Fixed, please verify.
