### ISSUE TITLE
Request: support for SAMD21 micro (Arduino's Zero/MKR1000 one)

### ISSUE THREAD

**Issue by q2dg** [cesanta/mongoose-os#183]
It would be fantastic!

**Comment by cpq** [comment]
32k RAM is too low to do reasonable things..
@q2dg do you work on some specific project on SAMD21 ?

**Comment by q2dg** [comment]
No. It was just a desire. But if you say 32k RAM isn't enough, needless to say more. 
Feel free to close this issue, therefore.
Thanks!!
