### ISSUE TITLE
Pass additional info to HTTP triggered updates

### ISSUE THREAD

**Issue by ceco** [cesanta/mongoose-os#184]
For HTTP-triggered updates, we need:

1. Access to the HTTP connection and message and a way to return results to the client:
struct mg_connection *nc;
struct http_message *hm = (struct http_message *) ev_data;

2. The result code and message of the OTA:

For e.g.

1    Update applied, finalizing
-1   Failed to create file
-2   Out of memory
-3   Update aborted
-4   Malformed archive (invalid file header)
-5   Wrong platform
etc.

**Comment by cpq** [comment]
@ceco is it still relevant for you?

**Comment by ceco** [comment]
This one is not relevant now.
Thanks.
