### ISSUE TITLE
How to call C++  functions directly by FFI?

### ISSUE THREAD

**Issue by aifer2007** [cesanta/mongoose-os#194]
How to call C++  functions directly by FFI?

**Comment by aifer2007** [comment]
I have wrote some codes to call cpp class method / cpp function from mos/mjs by ffi.
Work well. 
https://github.com/aifer2007/mos-mjs-cpp

**Comment by cpq** [comment]
Your CPP functions that you want to export should be wrapped into

```
extern "C" {
...
}
```

**Comment by aifer2007** [comment]
Thanks.
Yes, I have post a repo about calling cpp function by FFI.
