### ISSUE TITLE
Failed to fetch mos-esp8266.zip

### ISSUE THREAD

**Issue by deanmaniatis** [cesanta/mongoose-os#196]
$ mos --version
The Mongoose OS command line tool
Version: 2017022301
Build ID: 20170223-013339/lsm@c326da37

UI version: 20170223-013339/lsm@c326da37 

When choosing https://mongoose-os.com/downloads/mos-esp8266 from dropdown list i get the following error in the console 

```
Fetching https://mongoose-os.com/downloads/https://mongoose-os.com/downloads/mos-esp8266.zip...
```

and subsequently the download fails. If i add the ".zip" at the dropdown selection then it works.

**Comment by cpq** [comment]
Fixed, thank you

**Comment by deanmaniatis** [comment]
Thank you, commit fix reference?

**Comment by cpq** [comment]
That's done in the internal deployment script.
