### ISSUE TITLE
Honor DNS server from DHCP

### ISSUE THREAD

**Issue by kzyapkov** [cesanta/mongoose-os#199]
mos's DNS resolver implementation seems to explicitly use Google's 8.8.8.8 DNS server for lookups and doesn't honor DNS settings from DHCP. This doesn't work correctly in intranets or other environments where 8.8.8.8 is not accessible. Moreover, local resolving doesn't work.

**Comment by cpq** [comment]
@alashkin please implement

**Comment by alashkin** [comment]
For esp32 & esp8266 implemented in https://github.com/cesanta/mongoose-os/commit/e77fa53040e69050d18f28d6f9bb007231c01a57

**Comment by alashkin** [comment]
cc3200 implemented in https://github.com/cesanta/mongoose-os/commit/7a5b36dc27dc1c10c1912f71318a4ad015572c82

**Comment by fx** [comment]
@alashkin is this in `2.0+4ed5853~xenial0`? Seems to ignore the dhcp nameserver still.
