### ISSUE TITLE
Wifi "connect failed" in wizard mode 

### ISSUE THREAD

**Issue by jo-me** [cesanta/mongoose-os#205]
hi,
just wanted to follow your installation guide with my nodemcu, but the wizard fails on the wifi config step.
It says "connect failed"  without any more hints.

Is there maybe a problem with SSIDs containing special characters such as "!" or blank " "?

If I go to advanced mode and put my wifi settings there, it will eventually connect after an intial "connect failed" that runs through the console. 

Once it is connected though, I can reopen the wizard and click through it.

Thanks
Jochen

**Comment by cpq** [comment]
Could you try the latest mos version please?
