### ISSUE TITLE
[enhancement] Multiple MQTT brokers

### ISSUE THREAD

**Issue by muhlpachr** [cesanta/mongoose-os#207]
Use case: simultaneous cloud MQTT broker and local MQTT broker.
Local MQTT broker can serve local clients even in case of Internet connectivity outage.

**Comment by MobiusHorizons** [comment]
(honest question) Is that better than federating from the local MQTT broker to the cloud broker?

**Comment by muhlpachr** [comment]
No if you would like to "survive" with cloud broker updates/feeds in case of local broker failure.

**Comment by MobiusHorizons** [comment]
fair enough.

**Comment by cpq** [comment]
@muhlpachr is that what https://aws.amazon.com/greengrass/ is trying to do?

**Comment by cpq** [comment]
I am not sure that this fallback functionality should be on the Mongoose OS side.

If there is a local MQTT broker already, it makes sense for Mongoose OS to be configured to use it. Local broker should either forward traffic to the remote one, or spool if there is no connection.

**Comment by muhlpachr** [comment]
How local MQTT broker can do anything in case it dies (e.g. hw failure) ?

**Comment by cpq** [comment]
Fair question.

However, implementing fallback is a non-trivial task. How a failure is detected, at which point the switch happens, how to go back to the main target, should the device spool data locally if both targets fail and during the switch, etc etc.. Then, a fair question will arise - if done for MQTT, why not for HTTP? WebSocket? How authentication is handled? Security-wise, this is a huge potential for attacks.

So, the answer is: no fallbacks at this point in time.

**Comment by muhlpachr** [comment]
Why one would like to detect failure at client side if amount of traffic is not problem ?

Why client can not afford to establish more simultaneous connections to MQTT brokers ?

Why not HTTP or WebSocket ? Because there is not Pub/Sub abstraction. MQTT PUBLISH is not dependent on MQTT broker (address of MQTT broker is not used) and same for SUBSCRIBE.

MQTT has shadow service client and whole shadow abstraction does not have any issues with multiple parallel MQTT broker connections. 

Authentication data is just per MQTT broker configuration as it is now.

**Comment by muhlpachr** [comment]
AWS GreenGrass is for moving Lambda functions to on-premise compute resources (or to manage on-premise computer resources same way as Lambda functions).  Do you expect to implement availability cluster MQTT broker in Lambda functions ?

**Comment by markterrill** [comment]
Hi, I have a simple use case for being able to configure multiple MQTT servers.
Primary MQTT is GCP for command/control/status

Another MQTT is local for Home Assistant, ie mosquitto running on a customer's raspi.

Want to be able to selectively publish a message to a specific MQTT resource. Optional argument. If no argument it uses the default primary.

**Comment by rojer** [comment]
@markterrill interesting. please file as a new issue under https://github.com/mongoose-os-libs/mqtt

**Comment by markterrill** [comment]
> @markterrill interesting. please file as a new issue under https://github.com/mongoose-os-libs/mqtt
Cheers @rojer, have done so: 
https://github.com/mongoose-os-libs/mqtt/issues/14
