### ISSUE TITLE
[enhancement] NATS Pub/Sub Server/Client/Protocol

### ISSUE THREAD

**Issue by muhlpachr** [cesanta/mongoose-os#208]
Consider NATS client support, NATS Server embedding in mos binary and migration of UART transport to http://nats.io/documentation/internals/nats-protocol/

NATS protocol is simple enough to do all UART transport over NATS protocol (including console).
NATS server can be easily embedded into mos binary, is simple enough  and therefore can be started instantly with ability to support development of simple pub/sub clients without devices L3 addressing/namespace awareness.

**Comment by cpq** [comment]
That is unlikely going to happen in the nearest future. Most IoT cloud servers do not support it.
