### ISSUE TITLE
Any plan for supporting nRF5x?

### ISSUE THREAD

**Issue by nvl1109** [cesanta/mongoose-os#210]
Hi,

Thank you for your effort on this awesome OS. Do you have any plan to support nRF5x devices? Thank you.

**Comment by cpq** [comment]
the networking stack works on nRF, see  https://www.hackster.io/dfrank/mongoose-embedded-networking-library-on-nrf51-and-nrf52-547b15

both nRF51x and nRF52x

Could you elaborate on your project please?

**Comment by nvl1109** [comment]
Thank you for the info. I just think the nRF devices are very interest and useful in IoT projects (actually I'm studying & make some hobby development with nRF on Zephyr RTOS), so it is very nice if mongoose-os supports nRF devices.

**Comment by cpq** [comment]
Totally agree.

As soon as we get a commercial project on nRF platform, we'll port MongooseOS on it.
