### ISSUE TITLE
mos CLI does not support MQTT Password

### ISSUE THREAD

**Issue by neoautomata** [cesanta/mongoose-os#213]
The URL appears to be properly parsed via "net/url" and the user is retrieved, but the password is ignored. I think this can be solved by adding 3 lines into `common/go/mgrpc/codec/mqtt.go`:

```
        if u.User != nil {
                opts.SetUsername(u.User.Username())
+               if pass, ok := u.User.Password(); ok {
+                       opts.Password = pass
+               }
        }
```

**Comment by cpq** [comment]
@dimonomid please take this

**Comment by cpq** [comment]
Done in https://github.com/cesanta/mongoose-os/commit/e093e1d243bdecb2b84d8b6783ce4aa5aee6514f
