### ISSUE TITLE
Unable to connect Wifi

### ISSUE THREAD

**Issue by conniercarey** [cesanta/mongoose-os#219]
Using the Mongoose installer for the C3200 on a Launchpad.  It connects to COM port and flashes the firmware but when I got to setup the wifi I get "Error    context deadline exceeded".  I've verified my wifi network name and password.  Any ideas as to what is going on?  TIA

**Comment by cpq** [comment]
We've fixed some issues on cc3200, please try again - re-flash.

```
mos flash cc3200
mos wifi WIFI_NAME WIFI_PASS
```

Please let us know how it goes!
