### ISSUE TITLE
mDNS doesn't include an A record

### ISSUE THREAD

**Issue by kzyapkov** [cesanta/mongoose-os#220]
Oops, keyboard mishap.

Comparing mDNS responses as implemented in mgos with other implementations, we note that `avahi-browse` (and some other mDNS tools) don't properly show devices and their services. This is likely because the devices only reply with records for the services they advertise, but not a record to resolve their name to the IP.

**Comment by cpq** [comment]
Fixed in https://github.com/cesanta/mongoose-os/commit/992a2b6a37afa431960895acc4e81ebec6501d42

@kzyapkov please verify

**Comment by kzyapkov** [comment]
We've bumped to the latest revision of mongoose-os -- CC3200 builds fail with:

```
error #10056: symbol "mg_hash_md5_v" redefined: first defined in
   "/app/devices/dinrelay/.build/mongoose-os.a<mongoose.o>"; redefined in
   "/app/devices/dinrelay/.build/mongoose-os.a<cc3200_crypto.o>"
error #10056: symbol "mg_hash_sha1_v" redefined: first defined in
   "/app/devices/dinrelay/.build/mongoose-os.a<mongoose.o>"; redefined in
   "/app/devices/dinrelay/.build/mongoose-os.a<cc3200_crypto.o>"
error #10010: errors encountered during linking;
   "/app/devices/dinrelay/.build/dinrelay4.elf" not built
```

Looks like this happened along with the HTTP Auth refactoring, looks like an easy fix.

**Comment by cpq** [comment]
yes, @rojer please take a look

**Comment by rojer** [comment]
@kzyapkov make sure you have [this](https://github.com/cesanta/mongoose-os/blob/7a1e7e62feaab8de8c747d0eaf28e046a7a967ad/fw/platforms/cc3200/Makefile.build#L115) in your repo.
