### ISSUE TITLE
Update esp-idf to v2.0

### ISSUE THREAD

**Issue by JonnyBGod** [cesanta/mongoose-os#233]
Any planed timeframe for this?

**Comment by cpq** [comment]
Sure, we update.
@JonnyBGod what's your particular interest in updating, is there some specific functionality/fix you're looking for?

**Comment by JonnyBGod** [comment]
Need some of the fixes in Wifi and BT, in particular the promiscuous mode fix.

**Comment by JonnyBGod** [comment]
Are there instructions on how to compile with a new version of esp-idf?

**Comment by rojer** [comment]
@JonnyBGod we follow esp-idf pretty closely, the version we have in the build image at the moment is just a few days old - https://github.com/espressif/esp-idf/commit/3cad00fdcca7dd4b7939d7862407c000c29657c1

i tried to pull even more recent fixes, but in fact, ESP-IDF is currently broken: https://github.com/espressif/esp-idf/issues/520

i'm waiting for that bug to be fixed.
