### ISSUE TITLE
Inquiry: Is it Possible to Call the Native SDK API for the ESP8266 with mJS?

### ISSUE THREAD

**Issue by applecrusher** [cesanta/mongoose-os#239]
I would like to implement SPI TRAN on the ESP8266 using Mongoose OS. Since Mongoose OS doesn't have a unified API for this, I would like to call the SDK API directly. Does mJS support SDK API access directly to the devices? If so how is this done? I see on the forums that you can access the native SDKs, but I am not sure if I just need to use ffi or if there is something different I need to do. Your help is very much appreciated and thank you so much for all the good feedback you have given me so far!

**Comment by cpq** [comment]
1. clone mongoose-os repo
2. add your fw/mjs_api/api_whatever.js which FFI-es SDK functions you want
3. go to fw/examples/mjs_base and `mos build --repo ../../.. --local --verbose && mos flash`
4. now you can play with init.js as usual, with your new api
