### ISSUE TITLE
When updating settings via the http server, ajax calls to /conf/save do not respond

### ISSUE THREAD

**Issue by jmannau** [cesanta/mongoose-os#244]
I am using an ESP8266 and when trying to use the web configuration console to change settings, any ajax call to /conf/save does not return a response to the browser.

Steps to reproduce
1) Install the c_web_config example (https://github.com/cesanta/mongoose-os/tree/master/fw/examples/c_web_config)
2) Flash a device (I am using an ESP8266)
3) Open the Web Configuration Console (I use Safari 10.1 or Chrome 57)
4) Change a setting (i.e.: Device ID)
5) Open Web Inspector, Network Tab
6) Click Save Settings
7) The ajax to /conf/save does not return
8) The device console prints `save_cfg             Saved to conf9.json`
9) If you override the request by refreshing the page, the device reboots successfully.

**Comment by cpq** [comment]
Please follow https://forum.mongoose-os.com/index.php?p=/discussion/928/change-wifi-config-on-webpage#latest
