### ISSUE TITLE
mg_connect_ws() doesn't work

### ISSUE THREAD

**Issue by aifer2007** [cesanta/mongoose-os#246]
```c
struct mg_mgr *mgr = mgos_get_mgr();
struct mg_connection *nc = mg_connect_ws(mgr, MG_CB(ws_handler, NULL), server_url, NULL, NULL);
``` 
ws_handler() is defined:
```c
static void ws_handler(struct mg_connection *nc, int ev, void *ev_data, void *user_data){
  // do something
}
```
mg_connect_ws() always works well.

But to today, when I build with no errors, It never works, nc is NULL all the time.

**Comment by cpq** [comment]
See https://forum.mongoose-os.com/index.php?p=/discussion/comment/2177/#Comment_2177
