### ISSUE TITLE
Error with signature of Sys.malloc

### ISSUE THREAD

**Issue by mentlsve** [cesanta/mongoose-os#250]
Hi guys,

I wanted to run the neopixel example which did not work. In line 29 of [api_neopixel.js](https://github.com/cesanta/mongoose-os/blob/master/fw/mjs_api/api_neopixel.js) the function `Sys.malloc` is called with **1** argument
line 29: `data: Sys.malloc(numPixels * 3)`

If I look into [api_sys.js](https://github.com/cesanta/mongoose-os/blob/master/fw/mjs_api/api_sys.js) I can see in line 8 that the underlying `malloc` function expects **2**   arguments
line 8: `malloc: ffi('void *malloc(int, int)')`

This leads to the following error message:

```
mg_rpc_channel_uart  0x3fff08dc UART0
  at api_neopixel.js:29
  at init.js:5
mgos_app_init        MJS exec error: failed to call FFIed function: got 1 actuals, but function takes 2 args
```

Chaning line 8 in [api_sys.js](https://github.com/cesanta/mongoose-os/blob/master/fw/mjs_api/api_sys.js) from 
`malloc: ffi('void *malloc(int, int)')`
to
`malloc: ffi('void *malloc(int)')`
fixes the issue for me

**Comment by cpq** [comment]
Thank you.
That has been fixed.
Also, we've changed neopixel api to look more JS-y, see example at 
https://mongoose-os.com/project-videos.html#video4
