### ISSUE TITLE
Support for i2s?

### ISSUE THREAD

**Issue by mgleason** [cesanta/mongoose-os#252]
I don't think I've seen i2s support in Mongoose-OS.  But, @cpq says [here](https://github.com/cesanta/mongoose-os/issues/203) that the "native esp-idf SDK API is always available under MongooseOS"

Are there any examples of how to use the native esp-idf?  If not, can you give some instructions?  Is it simply a matter of adding `#include "driver/i2s.h" `?  Is there a specific path to the headers?

**Comment by cpq** [comment]
Answered in https://forum.mongoose-os.com/index.php?p=/discussion/comment/2335/#Comment_2335
