### ISSUE TITLE
C++ support?

### ISSUE THREAD

**Issue by neoautomata** [cesanta/mongoose-os#259]
Is C++ intended to be supported? The repo README  says "Code in C or JavaScript". It would be great to have access to all the Arduino compatible libraries (most of which are C++) without having to write a C compatibility layer to use classes.

Most things work, but there are two open issue for JSON_OUT_MBUF, and I just encountered the following:
```
In file included from /mongoose-os/common/platform.h:77:0,
                 from /mongoose-os/common/cs_dbg.h:9,
                 from src/main.cpp:21:
/mongoose-os/common/platforms/platform_esp8266.h:31:19: error: expected unqualified-id before '-' token
 #define fileno(x) -1
                   ^
```

This goes away and `mos build` succeeds if I rename `main.cpp` to `main.c`

**Comment by cpq** [comment]
main.c should be main.c,
but  you can add other  .cpp files at your will.
