### ISSUE TITLE
Versions are out-of-date

### ISSUE THREAD

**Issue by karimsa** [cesanta/mongoose-os#264]
Great work on this project, guys!

It seems that the tags/versions of mongoose-os are a bit out-of-date (`git log 1.2..HEAD --oneline | cat -n` seems to list 388 commits since v1.2, the last tagged commit).

This makes it a bit difficult to freeze our organization's project to a specific mongoose version. Are there any plans for how versioning is working going forwards? Is v1.3 in the works?

We have currently solved this issue by using a commit hash instead of using a version number - but this doesn't really fit with our policies of using semantic versioning.

**Comment by cpq** [comment]
We'll tag the repo roughly every ~4 weeks from now on.
