### ISSUE TITLE
Attach AWS Policies not working for GUI

### ISSUE THREAD

**Issue by applecrusher** [cesanta/mongoose-os#268]
When I go to the configuration on the GUI, I get the following error message on my console:

```
jquery.min.js:4 POST http://127.0.0.1:1992/policies 500 (Internal Server Error)
send	@	jquery.min.js:4
ajax	@	jquery.min.js:4
(anonymous)	@	VM928:31
j	@	jquery.min.js:2
k	@	jquery.min.js:2
```

I can't choose a policy.

**Comment by cpq** [comment]
Please remove ~/.aws/credentials, restart mos, and save credentials again

**Comment by cpq** [comment]
Please reopen if wiping / reinitialising the credentials did not help
