### ISSUE TITLE
DHT11 under mongoose OS does not works ...

### ISSUE THREAD

**Issue by vgrebenschikov** [cesanta/mongoose-os#277]
Exactly same wiring schema (trivial - only DHT11 sensor and ESP32 on devboard), same hardware ...

with plain ESP-IDF libraries and sample code from  Sam Johnston
it works fine, with Mongoose it fails on "Timeout waiting for start signal low pulse." 

on logic analyzer, signals looks similar (see screenshot) - on top - non-working capture from Mongoose and on bottom working with plain idf.

<img width="1394" alt="dht11-mongoose-vs-idf" src="https://cloud.githubusercontent.com/assets/3735671/26760191/046c4f0c-491b-11e7-8652-bb1b2948188a.png">

**Comment by vgrebenschikov** [comment]
Also, is there right way to make all DEBUG_PRINT and DEBUG_PRINTLN works?

**Comment by vgrebenschikov** [comment]
After applying the 

diff --git a/Adafruit_DHT/DHT.cpp b/Adafruit_DHT/DHT.cpp
index 78f48d8..4e97fcb 100644
--- a/Adafruit_DHT/DHT.cpp
+++ b/Adafruit_DHT/DHT.cpp
@@ -139,11 +139,11 @@ boolean DHT::read(bool force) {

   // Go into high impedence state to let pull-up raise data line level and
   // start the reading process.
+  pinMode(_pin, OUTPUT);
   digitalWrite(_pin, HIGH);
   delay(250);

   // First set data line low for 20 milliseconds.
-  pinMode(_pin, OUTPUT);
   digitalWrite(_pin, LOW);
   delay(20);

@@ -154,6 +154,7 @@ boolean DHT::read(bool force) {
     InterruptLock lock;

     // End the start signal by setting data line high for 40 microseconds.
+    pinMode(_pin, OUTPUT);
     digitalWrite(_pin, HIGH);
     delayMicroseconds(40);

**Comment by cpq** [comment]
@ruslanvaliullin is that addresset already ?

**Comment by ruslanvaliullin** [comment]
We need to go into high-Z state with pull-up. We should change to input mode, not to output mode and digitalWrite(_pin, HIGH). It's a known issue and will be addressed soon.

**Comment by vgrebenschikov** [comment]
Time to time it works, what is strange for me.

Do you think that it will work on other GPOI pin?
What pins are ready for pull-up? 
(is it right direction to dig into: https://www.esp32.com/viewtopic.php?t=439 ?)

**Comment by ruslanvaliullin** [comment]
@vgrebenschikov, the new DHT lib was implemented:

https://github.com/mongoose-os-libs/dht
usage examples:
https://github.com/mongoose-os-apps/example-dht-js
https://github.com/mongoose-os-apps/example-dht-c

Please check. Regards

**Comment by vgrebenschikov** [comment]
Thanks, now it works!
