### ISSUE TITLE
Does ESP32 have softap mode?

### ISSUE THREAD

**Issue by konyu** [cesanta/mongoose-os#282]
I found ESP8266 has softap mode.
https://github.com/cesanta/mongoose-os/blob/81bc17ed2c9f798860c51cbd548e2bff6957faff/fw/platforms/esp8266/src/esp_wifi.c#L72

but I didn't find esp32 has softap mode. Does ESP32 have softap mode?

**Comment by Galbi3000** [comment]
Looking at the code for the ESP32 it looks like it does have an AP mode, it's just called WIFI_MODE_AP instead of SOFTAP_MODE. On both they set mode_str = "AP"; so they must be the same mode ;)

**Comment by cpq** [comment]
Thanks @Galbi3000
