### ISSUE TITLE
ESP32 Analog IO

### ISSUE THREAD

**Issue by Galbi3000** [cesanta/mongoose-os#284]
Any idea when this feature of the ESP32 will be supported in Mongoose OS? And if it already is then how do I use it as I can not find anything in the documentation about it? I am using JavaScript.

**Comment by cpq** [comment]
For now, ADC API is not yet FFI-ed to JS, we expect it to be done next week.

**Comment by sctv** [comment]
Thanks
api_adc.js works nicely.
 Here is an example which reads an analog rain sensor when a button is pressed and publishes to the rain feed on a mqtt server. Sorry I can't get the insert code button to work with it.  

load('api_config.js');
load('api_gpio.js');
load('api_mqtt.js');
load('api_sys.js');
load('api_adc.js');

GPIO.set_button_handler(0, GPIO.PULL_UP, GPIO.INT_EDGE_NEG, 200, function() {
  let topic = Cfg.get('mqtt.user') + '/feeds/rain';
  let message = JSON.stringify(ADC.read(32));//reads pin 32 which is ADC1_CHANNEL_4 https://esp-idf.readthedocs.io/en/v2.0/api/peripherals/adc.html
  let ok = MQTT.pub(topic, message, 1);
  print('Published:', ok ? 'yes' : 'no', 'topic:', topic, 'message:', message);
}, null);

**Comment by sctv** [comment]
@ruslanvaliullin @cpq I am new to this... is the above what you mean by the ADC API being FFI-ed to JS?
Thanks

**Comment by ruslanvaliullin** [comment]
Yes that's it

**Comment by cpq** [comment]
Closing, as done.
