### ISSUE TITLE
RPC: MQTT response doesn't go back to specified "src" topic

### ISSUE THREAD

**Issue by scotthernandez** [cesanta/mongoose-os#291]
The docs stay that the src field in the request is the topic that the response will be sent to, but it actually sends the response to the "{src}" + "/rpc" topic: https://mongoose-os.com/docs/libraries/core/rpc.html#mg-rpc-frame-format

I believe either the docs are incorrect, or the code is.

I'd rather see the code changed to reply back to the src as is, without any change. It is kinda weird to get a response on what I think of as the rpc "listener" topic.

**Comment by dimonomid** [comment]
Thanks for reporting; at least for now the code is going to stay intact, fixed docs.
