### ISSUE TITLE
WebUI: Do not include git info on project:lib/app copy

### ISSUE THREAD

**Issue by scotthernandez** [cesanta/mongoose-os#293]
If a project:lib/app is cloned it should not point to the original git source.

Perhaps there should be an option to copy over git info, but it should not be the default option.

**Comment by dimonomid** [comment]
Why not? After cloning we might want to e.g. get some updates from upstream, etc. If we want to push to some other location, we could add another git remote (or indeed replace existing one), but I don't see why keeping the actual origin should not be the default.
