### ISSUE TITLE
Unable to download firmware (esp8266)

### ISSUE THREAD

**Issue by Aterocana** [cesanta/mongoose-os#295]
The issue is still there unluckily.
https://github.com/cesanta/mongoose-os/issues/212

**Comment by snpwr** [comment]
+1

On up-to-date Manjaro (which is essentially Arch Linux) with Kernel 4.11

**Comment by snpwr** [comment]
Seems that it has to do with the DNS resolver.

It works when forcing it to use the pure-go dns resolver:
`GODEBUG=netdns=go /path/to/mos`

Whereas it shows the described behavior when using the cgo resolver:
`GODEBUG=netdns=cgo /path/to/mos`

**Comment by dimonomid** [comment]
@snpwr , thanks for reporting and for figuring the DNS issue; mos 1.10 is built with forced pure-go dns resolver.
