### ISSUE TITLE
Support with esp8266 for Wiznet 5100 or ENC28J60!

### ISSUE THREAD

**Issue by tusharvb19** [cesanta/mongoose-os#301]
I want to use Ethernet interface along with os for its features!
Need help!
TIA

**Comment by tectiv3** [comment]
I started working on it:
https://github.com/tectiv3/lwip-enc28j60-app
https://github.com/tectiv3/lwip-enc28j60
It is a work in progress as currently I can't initiate connections from mongoose.

**Comment by cpq** [comment]
@rojer please integrate once @tectiv3 finishes

**Comment by tusharvb19** [comment]
Waiting for the Ethernet support...LAN8720 and Wiznet5100😊

**Comment by cpq** [comment]
Done for esp32.

**Comment by tusharvb19** [comment]
what about esp8266? If I want to connect it with W5100 or other Ethernet chip?

**Comment by cpq** [comment]
@tusharvb19 , your contribution of ethernet support for esp8266 would be welcome.

**Comment by tusharvb19** [comment]
It uses SPI and has ready arduino ethernet library.
But how to use in mongoose os?
