### ISSUE TITLE
Timer.now() on ESP8266 Showing Uptime

### ISSUE THREAD

**Issue by applecrusher** [cesanta/mongoose-os#302]
When I try to get the current time for the device on bootup using `Timer.now()` with mjs, equivalent c is `double mg_time(void)` I am getting a very small decimal number, 1.180701 on bootup. I have been experimenting around with this and it seems as though before the timer current time i set, it is giving uptime.

**Comment by cpq** [comment]
That's working as intended. Until the device gets the time via SNTP, its hardware timer counting time from the boot time.
