### ISSUE TITLE
OneWire doc & example is missing

### ISSUE THREAD

**Issue by muhlpachr** [cesanta/mongoose-os#303]
Example https://github.com/cesanta/mongoose-os/tree/master/fw/examples/c_arduino_onewire mentioned in #117 is missing. 
Doc for OneWire is missing https://mongoose-os.com/docs/

**Comment by cpq** [comment]
Fixed links, and added doc, not the best doc i've seen so far, but anyways
https://mongoose-os.com/docs/libraries/arduino/arduino-onewire.html
