### ISSUE TITLE
Disabling RPC Bricks Device

### ISSUE THREAD

**Issue by benr** [cesanta/mongoose-os#305]
I just noticed this issue while trying to reduce activity during some testing.  I'm using a NodeMCU 1.0 ESP8266 with the latest Mongoose (20170630-153645).   

When I set rpc.enabled=false, the device reloads the configuration and then after reboot spews garbage and no longer is usable.  Web UI also becomes unusable, CPU on my workstation spikes and Chrome eventually offers me a dialog to kill the tabs containing Mongoose UI.  To regain control I must do a fresh reflash the device from the CLI.  

Attached is a screenshot of the Mongoose UI after reboot:

<img width="600" alt="mongoose-rpc enabled-issue" src="https://user-images.githubusercontent.com/14073/27773255-8a3e2a86-5f2a-11e7-8b00-4d9bd2c5752e.png">

**Comment by cpq** [comment]
@rojer please handle this one
