### ISSUE TITLE
MOS firmware build problem  

### ISSUE THREAD

**Issue by Sparow199** [cesanta/mongoose-os#309]
Hello ,

I have the last version of `mos`,  month ago, i had made a project called [MQ-135](https://github.com/Sparow199/MQ135_MONGOOSE_OS) **and i had test it and it worked.**

**Today, i cloned my repository, and i tried it , it doesn't work !!!**

**Procedure:**
`mos build --arch esp8266` success 
`mos flash` success 
`mos console` show nothing 
`mos ui` error message on mos tools log
`E0708 00:10:55.416357   11834 ui.go:456] Calling: FS.ListExt
Server Error: {"error":"Device is not connected"}
Loaded https://mongoose-os.com/downloads/api.json
E0708 00:11:00.919467   11834 ui.go:456] Calling: Sys.GetInfo
E0708 00:11:06.092541   11834 reconnect_wrapper.go:72] [reconnectWrapperCodec to /dev/ttyUSB0; connecting...] Connection closed
E0708 00:11:06.092592   11834 ui.go:480] Call complete, error: context deadline exceeded`

I tried on Mac OS and Ubuntu, ArchLinux, Debian with ESP8266 and ESP32 using examples from Mongoose OS repository but nothing worked.

I flashed my esp8266 and ESP32 with default firmware then i uploaded my `init.js` and `api_mq.js` files, it works !!! But there is a lot of unused files inside the ESP8266 with default firmware.

**Comment by riless** [comment]
Just read the error.

`mjs_exec_file` does not take `generate_jsc` as a third parameter [anymore](https://github.com/cesanta/mjs/commit/88b387b60595f57db0fb6b6b94b682dac666865d#diff-dfd500dfec3905a96aff2852116f6fe1L8084).

You should replace [this line ](https://github.com/Sparow199/MQ135_MONGOOSE_OS/blob/master/src/main.c#L40)by:

```
mjs_err_t err = mjs_exec_file(mjs, "init.js", NULL);
mjs_set_generate_jsc(mjs, 1);
```

**Comment by Sparow199** [comment]
@riless thank you for the correction, i modified the issue in order to simply it and focus on the main problem, because it doesn't work  with whole projects not only mines.

**Comment by cpq** [comment]
We have refactored mos architecture a bit, now it has apps and libraries.

@Sparow199 do you mind contributing that example under the Apache 2.0 license, per https://mongoose-os.com/docs/overview/apps.html#contributing-an-app-or-library ?

If you're fine with that, I'll move your app and fix the build.

**Comment by Sparow199** [comment]
@cpq thank you for reply, i'll try the build process next Monday  and i'll keep you informed about issue.
 I'll contribute with my library soon.

**Comment by Sparow199** [comment]
@riless @cpq , it works with last MOS update.
THANK YOU

**Comment by cpq** [comment]
@Sparow199 do you mind me adding your app to the mongoose-os-apps collection under the Apache 2.0 license?

**Comment by Sparow199** [comment]
@cpq  it will be available soon

**Comment by cpq** [comment]
https://github.com/mongoose-os-libs/mq135 - you have admin rights.
Feel free to import there.
Don't forget to set the description, yourself as an author, and Apache2.0 license, please.

Thank you!
