### ISSUE TITLE
Failed to compile mjs http server example

### ISSUE THREAD

**Issue by Sparow199** [cesanta/mongoose-os#310]
I tried to compile this [MSJ HTTP Server](https://github.com/cesanta/mongoose-os/blob/master/fw/examples/mjs_base/examples/http_server.js) but no way.
Error message:
`mgos_http_server_ini HTTP server started on [80]
esp32_bt_gatts_ev    Starting BT service 5f6d4f53-5f52-5043-5f53-56435f49445f
mg_rpc_channel_mqtt  0x3ffe332c esp32_023888/rpc/#
 mg_rpc_channel_uart  0x3ffe38e0 UART0
mgos_init            Init done, RAM: 227760 total, 115516 free, 115516 min free
  at init.js:16
MJS error: calling non-callable
mongoose_poll        New heap free LWM: 102796`

I tried with last version of MOS with ESP32 and ESP8266.

**Comment by cpq** [comment]
Please don't use that deprecated code.
I suggest to use RPC to implement RESTful services
