### ISSUE TITLE
OTA update on esp8266 fails

### ISSUE THREAD

**Issue by kzyapkov** [cesanta/mongoose-os#317]
Trying to update a NodeMCU v2 module with `https://github.com/mongoose-os-apps/default` fails with a weird crash. After the failed update the module no longer boots.

This happens regardless of which OTA mechanism is used -- UART RPC, HTTP fetch, HTTP POST. It is also reproducible with other apps, even with the bare-bones `c_hello` example, both local and cloud builds.

**Comment by rojer** [comment]
fixed by https://github.com/cesanta/mongoose-os/commit/9faa8bd3a2cfd5419d5657dd5a4130486d98cf93 and https://github.com/cesanta/mongoose-os/commit/7bba6c6546d9132033c8de3d7e3629a36a53a854
