### ISSUE TITLE
There is no tags in WIFI lib so firmware can not be build 

### ISSUE THREAD

**Issue by phush0** [cesanta/mongoose-os#322]
There is no tags in WIFI lib, so there is no version 1.10 `mos build` will return:
`Error: failed to git checkout 1.10: error: pathspec '1.10' did not match any file(s) known to git.`

**Comment by phush0** [comment]
it is fixed please close

**Comment by dimonomid** [comment]
Yeah thanks for reporting, the real issue back then was that released mos (1.10 in your case) was trying to build latest apps, so newly added libs were breaking the release build. Now it's fixed.
