### ISSUE TITLE
OTA on ESP8285 fails

### ISSUE THREAD

**Issue by kzyapkov** [cesanta/mongoose-os#323]
When
```
arch: esp8266
build_vars:
  FLASH_SIZE: 1048576
```

we get

`-5 OTA is not supported in this build`

**Comment by kzyapkov** [comment]
So, it seems the new flash layout doesn't allow for OTA on 1MB flash chips:

```
#
# 1MB (8Mb) layout:
#
# 0x000000 - rBoot        |
# 0x007000 - boot cfg     |
# 0x008000 - app (844K)   |
# 0xdb0000 - fs (128K)    |
# 0x0fb000 - rf cal       |
# 0x0fc000 - sys params   |
```

Is there no way to use smaller slots for FS and application?

**Comment by rojer** [comment]
i think we discussed this on gitter. ufortunately, there really is no way to squeeze mos with useful functionality into 1MB flash.
