### ISSUE TITLE
FR: Need mqtt 'retain' for publish and will

### ISSUE THREAD

**Issue by kc2h** [cesanta/mongoose-os#327]
All of our MQTT projects create a "units/{device_id}/status" channel so that our control apps know the status of any device immediately, specially in the event of a control app restart.  The control apps also push some updates using retain so an offline device can update as soon as it's back online.

**Comment by dimonomid** [comment]
Implemented in latest: https://github.com/mongoose-os-libs/mqtt/commit/9fefa78b321f2bb8a2e640a24aa6182e721bd25b , will be included in the upcoming release 1.15.
