### ISSUE TITLE
Update example mos.yml

### ISSUE THREAD

**Issue by pherris** [cesanta/mongoose-os#329]
This line in the example yml file:
 `  # build/sys_config.c or build/sys_config.h file.`should be changed to
 `  # build/gen/sys_config.c or build/gen/sys_config.h file.`

https://github.com/cesanta/mongoose-os/blob/master/fw/skeleton/mos.yml#L29

My `mos` version:

```
✗ ~/.mos/bin/mos --version 
The Mongoose OS command line tool
Version: 1.12
Build ID: 20170801-122629/1.12@c274dea8
Update channel: release
```

**Comment by dimonomid** [comment]
Thanks for reporting; that skeleton mos.yml is not used anymore, we use [empty app](https://github.com/mongoose-os-apps/empty) instead, which I recently updated as you mentioned.
