### ISSUE TITLE
Read output pin state

### ISSUE THREAD

**Issue by pgspulpi** [cesanta/mongoose-os#333]
Actually, reading output pin state change the pin mode to "input" and set the state to low. This makes difficult to show/get output states for remote access or embedded web app. This is a common scenario so changing this behavior is more than interesting.
In addition, I think the fact that a "read" API call can change device configuration (like pin mode) makes no sense to me and should be done explicitly.

**Comment by cpq** [comment]
W.r.t. read api - we think that's the right way.
Reading from a pin in a output mode does not make sense. And not everybody is careful enough to make sure the mode is always correct.

We can consider the API for getting the current mode.
