### ISSUE TITLE
FR: dns server 

### ISSUE THREAD

**Issue by jocodeinc** [cesanta/mongoose-os#336]
When connected to device (e.g., ESP8266_12345), user can access index.html (similar to wifi-setup app) using fake domain name (e.g., setup.mongoose.com) rather than 192.168.4.1

It'll make it easier for user (non-techie) to interact with the setup rather than using IP address.

**Comment by cpq** [comment]
This is important for usability.
@ruslanvaliullin take on this one.

**Comment by wormyrocks** [comment]
This and softAP redirect are also crucial to my project. As far as I can tell neither of the existing captive portal examples for the esp32 will even redirect websites that use https.

**Comment by dimonomid** [comment]
Resolved with https://github.com/mongoose-os-libs/wifi/commit/ad19f7ac63b484ccd3047b7c9823589dbef021b1
