### ISSUE TITLE
Slowdown/hand after configuration/init.js save

### ISSUE THREAD

**Issue by luseengithub** [cesanta/mongoose-os#339]
I have got NodeMCU esp8266. The app which I am running was working very fine until today. 
Steps which I am doing:
- mos flash  - no issues
- mos ls  -no issues
- opening browser and connecting to the board without wifi setup - no issues
- selecting init.js and selecting Save and Reboot

After this device gets very slow, after restarting and connecting to the web if prints different characters, like memory dump.                                              

<img width="1440" alt="screen shot 2017-08-28 at 00 15 53" src="https://user-images.githubusercontent.com/25040099/29755074-a560443a-8b89-11e7-9a74-0c174522942f.png">
<img width="1440" alt="screen shot 2017-08-28 at 00 16 18" src="https://user-images.githubusercontent.com/25040099/29755075-a57a4100-8b89-11e7-85bc-9b0f9420802a.png">
<img width="1440" alt="screen shot 2017-08-28 at 00 34 47" src="https://user-images.githubusercontent.com/25040099/29755076-a57aca44-8b89-11e7-82d2-2ca6079fc7b5.png">

Dump is:
[Aug 28 01:23:11.825] esp_mgos_init2       mjs_base 1.0 (20170827-231217/???)
[Aug 28 01:23:11.830] esp_mgos_init2       Mongoose OS 2017082723 (20170827-231217/???)
[Aug 28 01:23:11.836] esp_mgos_init2       SDK 2.1.0(ce90efd); flash: 4M; RAM: 52152 total, 49284 free
[Aug 28 01:23:11.843] esp_print_reset_info Reset cause: 4 (soft reset)
[Aug 28 01:23:11.848] mgos_vfs_dev_open    sysflash () -> 0x3ffeffa4
[Aug 28 01:23:11.852] mgos_vfs_mount       Mount SPIFFS @ / (dev 0x3ffeffa4, opts {"addr": 32768, "size": 262144}) -> 0x3ffeffb4
[Aug 28 01:23:11.920] mgos_vfs_mount       /: size 233681, used: 112699, free: 120982
[Aug 28 01:23:12.010] mgos_sys_config_init MAC: 5ECF7FEEB5F7
[Aug 28 01:23:12.014] mgos_sys_config_init WDT: 30 seconds
[Aug 28 01:23:12.018] mgos_mdns_init       Listening on udp://:5353
[Aug 28 01:23:12.023] mgos_mdns_hal_join_g Joining multicast group 224.0.0.251
[Aug 28 01:23:12.029] mgos_aws_init        AWS Greengrass enable (0)
[Aug 28 01:23:12.034] scandone
[Aug 28 01:23:12.035] del if0
[Aug 28 01:23:12.036] usl
[Aug 28 01:23:12.036] mode : null
[Aug 28 01:23:12.037] mgos_wifi_set_config WiFi mode: off
[Aug 28 01:23:12.041] mgos_http_server_ini HTTP server started on [80]
[Aug 28 01:23:12.049] mg_rpc_channel_mqtt  0x3fff1124 esp8266_EEB5F7/rpc/#
[Aug 28 01:23:12.056] mg_rpc_channel_uart  0x3fff149c UART0
[Aug 28 01:23:12.060] mgos_init            Init done, RAM: 52152 total, 43620 free, 42712 min free
[Aug 28 01:23:13.257] LED GPIO: 2; button GPIO: 0
[Aug 28 01:23:13.471] save_cfg             Saved to conf9.json
[Aug 28 01:23:13.482] Saving configuration: no error
[Aug 28 01:23:13.499] mongoose_poll        New heap free LWM: 22088
[Aug 28 01:23:14.494] reconnect
[Aug 28 01:23:14.495]
[Aug 28 01:23:14.496] Exception 28 @ 0x4000df2f, vaddr 0x00000033
[Aug 28 01:23:14.500]  A0: 0x400018bc  A1: 0x3ffffe20  A2: 0x3ffeffd6  A3: 0x00000033
[Aug 28 01:23:14.505]  A4: 0x00000006  A5: 0x3ffeffd6  A6: 0x0000ffff  A7: 0x00000000
[Aug 28 01:23:14.511]  A8: 0x00000003  A9: 0x00000001 A10: 0x80000000 A11: 0x7fffffff
[Aug 28 01:23:14.516] A12: 0x3ffeffcc A13: 0x3ffef534 A14: 0x402028a4 A15: 0x3ffef4dc
[Aug 28 01:23:14.522]
[Aug 28 01:23:14.522] (exc SP: 0x3ffffc80)
[Aug 28 01:23:14.524]
[Aug 28 01:23:14.524] --- BEGIN CORE DUMP ---
[Aug 28 01:23:14.527] {"arch": "ESP8266",
[Aug 28 01:23:14.528] "REGS": {"addr": 1073740976, "data": "

**Comment by luseengithub** [comment]
Looks like crash happens after saving the configuration:

`int disable_wifi_ap (void) {
  struct sys_config *cfg = get_cfg();
  cfg->wifi.ap.enable = false;
  char *err = NULL;
  save_cfg(cfg, &err); /* Writes conf9.json */
  printf("Saving configuration: %s\n", err ? err : "no error");
  free(err);
  return 0;
}`

What is wrong in this code?

**Comment by cpq** [comment]
Please show your whole init.js
