### ISSUE TITLE
FR: get mongoose-os module path from mos tool

### ISSUE THREAD

**Issue by iH8c0ff33** [cesanta/mongoose-os#348]
It would be really useful, for things such as an editor extension, if it was possible to get the (absolute) path of the mongoose-os module, which usually is `$HOME/.mos/modules-<version>/mongoose-os<version>`, in a dynamic way so that it's possible to get that path in every system with mos tool installed.

**Comment by cpq** [comment]
Done

```
mos update latest
mos -X get-mos-repo-dir
```
