### ISSUE TITLE
c_web_config example doesn't work

### ISSUE THREAD

**Issue by bguban** [cesanta/mongoose-os#350]
c_web_config example is broken.

PS examples are the best documentation. Try to keep them in a good state. Thanks.

**Comment by cpq** [comment]
Could you be more specific please.
What exactly is broken, what browser you're using, etc.

**Comment by bguban** [comment]
![screenshot 2017-09-12 11 32 29](https://user-images.githubusercontent.com/1564376/30315975-4248d08e-97ae-11e7-9b4a-988b3968ed0d.png)
I've flashed the example to my esp8266 and went to it's web page. But there is only list of files instead of configuration page. I checked git log and found that index page was removed.

**Comment by cpq** [comment]
Got it.

Don't use things from `fw/examples`, that's deprecated stuff.
https://mongoose-os.com/apps.html please. There is a web ui setup app.

**Comment by bguban** [comment]
Thanks
