### ISSUE TITLE
Add Flag to Remove Device Id from MQTT endpoint

### ISSUE THREAD

**Issue by applecrusher** [cesanta/mongoose-os#351]
Hey All,

I am trying to remove the device id from MQTT endpoint, but it seems to get added automatically.

A reason to use this is because, for example, AT&T uses the following endpoint format:

> m2x/M2X API Key/requests

But filling it out in the mqtt section will always have it end with m2x/M2X API Key/requests/id

If this can be done another way, how?

**Comment by cpq** [comment]
@applecrusher could you elaborate please? What exactly you're doing?

**Comment by applecrusher** [comment]
I am trying to implement MQTT on the AT&T IOT platform, which doesn't end with the device id. 

[https://m2x.att.com/developer/documentation/v2/mqtt](https://m2x.att.com/developer/documentation/v2/mqtt)

**Comment by cpq** [comment]
That's understood, thank you.

I still don't understand why do you think mOS appends anything to the MQTT topics.
If you're talking about disabling RPC over mqtt, do `rpc.mqtt.enable=false`.
Otherwise, mOS does not append anything to your MQTT topics.

**Comment by applecrusher** [comment]
Ok. I got confused and thought the MQTT device address was the same as the MQTT server endpoint.
