### ISSUE TITLE
Is there a way to Disable Mongoose Access Point?

### ISSUE THREAD

**Issue by vpetrache** [cesanta/mongoose-os#361]
Hello,

Is there a way to disable the ESP8266 to create a wifi Access Point, called Mongoose with default password Mongoose?
Through that access point one gets access to my wifi, aws and mqtt credentials..

**Comment by bravokeyl** [comment]
@vpetrache Yes, disable `wifi.ap` in the config

**Comment by vpetrache** [comment]
Awesome, thanks so much!
