### ISSUE TITLE
Problem with flashing ESP32

### ISSUE THREAD

**Issue by pankleks** [cesanta/mongoose-os#364]
Model ESP32 DevKitC

Connected - USB drivers installed.

![image](https://user-images.githubusercontent.com/14176066/31546413-7c519710-b023-11e7-945c-0d005041fdf6.png)

After getting `context deadline exceeded` flash button becomes enabled again - and that's it ... :(

**Comment by farooqhasny** [comment]
i think you need to put ESP32 in flash mode by grounding GPIO0 and booting up .

**Comment by dimonomid** [comment]
should be fixed now, feel free to reopen if it still fails for you
