### ISSUE TITLE
mos-esp8266-1M-1.18 404

### ISSUE THREAD

**Issue by dragouf** [cesanta/mongoose-os#368]
with mongoose os 1.18 on windows 10 and ESP-01 1M.
seems mos will try to download `mos-esp8266-1M-1.18` and it failed with 404. 

Change to `mos-esp8266-1M-latest` will succeed but then esp-01 device return :

`[Oct 18 08:38:15.638]  !cg m cSjR ;bS- ! ngccR !c k kcCnJB`
![image](https://user-images.githubusercontent.com/62718/31704029-c0f5249e-b3df-11e7-8212-4718c08d5172.png)

**Comment by dimonomid** [comment]
Now it should be fixed
