### ISSUE TITLE
mos.exe ui, fails to load default browser

### ISSUE THREAD

**Issue by sh4nnongoh** [cesanta/mongoose-os#372]
Running the command `./mos.exe ui` will initiate a deadlock process.
The only way to get a UI out is to double click the `mos.exe`

I am using Windows 10 with the latest mos build.

**Comment by dimonomid** [comment]
Can't reproduce, `mos.exe ui` opens the browser just fine. Does it still reproduce for you?

**Comment by dimonomid** [comment]
Closing this for now; please feel free to reopen if it still doesn't work for you.
