### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by adrianz** [cesanta/mongoose-os#378]
Please consider making an official [Homebrew](https://brew.sh) formula for Mongoose in order to make installation and updates for macOS users much easier.

Homebrew is

> The missing package manager for macOS

and *de facto* standard on macOS for distributing CLI tools.

Instructions are available in [Formula Cookbook](https://docs.brew.sh/Formula-Cookbook.html).

**Comment by dimonomid** [comment]
Here you go: https://github.com/cesanta/homebrew-mos

```c
$ brew tap cesanta/mos
$ brew install mos
```
