### ISSUE TITLE
Custom Mongoose OS build

### ISSUE THREAD

**Issue by techparva** [cesanta/mongoose-os#383]
I am newbee to Mongoose OS. I am trying to write a firmware for ESP8266 based device with 1M flash. It seems OTA is not possible because size of the firmware is too big to hold both firmware in such size. I don't need more than 4k of file system as I don't wish to keep much data in file system.
Can someone tell how to reduce size of the firmware further so that 2 firmwares can fit and we can enable OTA?
How do we see what all components are being built inside firmware and how to disable any components what I may not need?
I also tried to build an empty app and empty.elf size is hardly 3 to 4kb, whereas empty.in is 493kb. Can someone tell me why size differs so much?

**Comment by dimonomid** [comment]
> empty.elf size is hardly 3 to 4kb
Not sure which empty.elf you mean, since its size is more than 3MB:
```
ls -lh build/objs | grep empty 
-rw-r--r-- 1 dimon dimon 590K Dec 12 19:53 empty.bin
-rwxr-xr-x 2 dimon dimon 3.4M Dec 12 19:53 empty.elf
-rw-r--r-- 1 dimon dimon 3.6M Dec 12 19:53 empty.elf.map
```
And no, I don't think it's possible to cut much from an empty app.
