### ISSUE TITLE
Resurrect MGOS_UPD_EV_BEGIN

### ISSUE THREAD

**Issue by kzyapkov** [cesanta/mongoose-os#411]
e473ee160389abb72218e changes the way update callbacks are invoked and (possibly unintentionally) drops `MGOS_UPD_EV_BEGIN`. This used to allow user code access to manifest data and ability to reject updates.

Please restore this functionality. A minimally-invasive solution is here:

https://github.com/kzyapkov/mongoose-os/tree/resurrect_upd_begin_event

**Comment by rojer** [comment]
looks good, i will apply the change.
thanks!

**Comment by kzyapkov** [comment]
Hey @rojer, @cpq, did this just happen again?

**Comment by cpq** [comment]
Fixed by https://github.com/cesanta/mos-libs/commit/e9f84a15ae934097224c860f9ef46fdd2e5f31d3
