### ISSUE TITLE
Bug in mgos_uart.c in function mgos_uart_config_set_tx_params

### ISSUE THREAD

**Issue by ulso** [cesanta/mongoose-os#416]
https://github.com/cesanta/mongoose-os/blob/f8064c01bc44cf0e3c86161d6bd893cc644275e9/fw/src/mgos_uart.c#L243

On line 243 in mgos_uart.c, in function mgos_uart_config_set_tx_params. Currently that line says:
`  cfg->rx_fc_type = (tx_fc_ena ? MGOS_UART_FC_HW : MGOS_UART_FC_NONE);`
I suspect it should really be:
`  cfg->tx_fc_type = (tx_fc_ena ? MGOS_UART_FC_HW : MGOS_UART_FC_NONE);`

**Comment by rojer** [comment]
indeed. fix sent!
