### ISSUE TITLE
OTA rpc reverts

### ISSUE THREAD

**Issue by AlessiaPileri** [cesanta/mongoose-os#426]
I'm using mongoose-os on ESP32 platform and I have an issue trying to perform OTA update via RPC http (I'm using licensed version of the lib).
After the rpc command, OTA update seems to be ok,as I can see in the mos console:
``updater_finish       Finished: 1 Update applied, finalizing ``
But after few minutes I see this message in mos console:
``OTA failure: reverting``
and firmware version is reverted.

Full log downloaded from ``mos console``:  [log_mos.txt](https://github.com/cesanta/mongoose-os/files/1990934/log_mos.txt)

**Comment by cpq** [comment]
Did you `OTA.Commit` the new firmware after boot ?

**Comment by AlessiaPileri** [comment]
Should I send OTA.Commit command explicitly? In past versions of the libs, send OTA.Update was enough to update the firmware.

**Comment by cpq** [comment]
Please read https://mongoose-os.com/docs/book/ota.html and https://github.com/mongoose-os-libs/rpc-service-ota#otaupdate

**Comment by cpq** [comment]
Closing this - feel free to reopen if required.
