### ISSUE TITLE
Interrrupts are skipped when occurring with high processing load

### ISSUE THREAD

**Issue by mamuesp** [cesanta/mongoose-os#433]
@cpq - As discussed in Gitter, it would be helpful to increase the amount of the INT queue so that there might be a balance between INT "flooding" and INT "ignoring" when the system is busy otherwise. You asked for an issue to may set the right prio, so here it is! ;-)

**Comment by tripflex** [comment]
+1

**Comment by mamuesp** [comment]
Yeah, it's good to bring that in mind, because interrupts and MJS are not really friends these days ... ;-)

**Comment by cpq** [comment]
PR please!

**Comment by mamuesp** [comment]
@cpq - We discussed that (I believe @rojer was into the discussion as well, if I remember correctly), and from your side came the question to post an issue so that you or @rojer will look after this problem as soon as possible (this was the promise then ...) ;-) - because it's not an excpected behaviour that interruts are going down the drain in MJS. So this is no complaining about missing features but a really (nearly) faulty behaviour and a fix was proposed from your (or @rojer's) side. So how could I provide a PR at this place? There was also a concrete idea to pass a parameter when settings the interrupt handler so one may increase the queue for the interrupts.

**Comment by rojer** [comment]
i believe i have a fix for this, about to send a PR

**Comment by mamuesp** [comment]
:+1:
