### ISSUE TITLE
DNS from DHCP server is not used in "latest"

### ISSUE THREAD

**Issue by mamuesp** [cesanta/mongoose-os#434]
When using mos latest, the SNTP and/or MQTT connections are failing because of DNS problems, suddenly using Googles DNS "8.8.8.8" - which on my settings is not always reachable (with purpose). My DHCP server provides obviously another DNS server, but it's ignored, also some hardcoded server in the configuration will be without effect. With the release version there is no problem, so it seems to be a new bug.

According to @nliviu, `mgos_get_nameserver()`returns NULL, because `MGOS_HAVE_WIFI`is not set.

**Comment by rojer** [comment]
fixed by https://github.com/cesanta/mongoose-os/commit/f3c448285a72a3dcaee4d1bf2a6768222193a402 and
