### ISSUE TITLE
ESP8266 GPIO Pinout Diagram

### ISSUE THREAD

**Issue by salmanfarisvp** [cesanta/mongoose-os#436]
Can any one share the Pinout diagram of esp8266 in mongoose-os , can't find it anywhere .

**Comment by tripflex** [comment]
I'm not sure what you mean by this? ESP8266 GPIO pins are not modified by MOS, that is all based on the chip and whatever dev board you may be using ....

https://www.esp8266.com/wiki/doku.php?id=esp8266_gpio_pin_allocations

https://www.espressif.com/sites/default/files/documentation/esp8266-technical_reference_en.pdf

**Comment by pimvanpelt** [comment]
agreed with @tripflex that this question is out of place for Mongoose OS. It uses the GPIO mapping as defined by ESP8266 and ESP32 and CC32x0 and STM32 chips. How these are routed to pins in a breakout board, like the ones he mentioned, are a matter of the breakout board vendor, not Mongoose OS.

By means of an example for a popular ESP32:
https://github.com/playelek/pinout-doit-32devkitv1/blob/master/pinoutDOIT32devkitv1.png

these diagrams show the relationship between ESP32 pinout and breakout board pins. You'll have to consult your hardware vendor for the correct mapping, not Mongoose OS.
