### ISSUE TITLE
needs sudo on macOS

### ISSUE THREAD

**Issue by DanielRuf** [cesanta/mongoose-os#444]
The install script needs sudo to create the missing directories on macOS 10.13.
```
/usr/local/opt/libftdi/lib/
/usr/local/opt/libusb/lib/
```

And also
```
sudo curl -fsSL https://mongoose-os.com/downloads/mos-$VERSION/`basename $1` -o "$1"
```

**Comment by mybigman** [comment]
why not use brew? It works nicely.

**Comment by DanielRuf** [comment]
> The install script

I do not use `brew` in this case.
It should work on all ways.
