### ISSUE TITLE
MacOS brew tap cesanta/mos step missing in https://mongoose-os.com/software.html?

### ISSUE THREAD

**Issue by FerventGeek** [cesanta/mongoose-os#449]
Installing on Mac, mos isn't in the default home-brew formula list. Running `brew tap cesanta/mos` per https://github.com/cesanta/homebrew-mos solves this, but it's not included on the main download page on https://mongoose-os.com/software.html, or easy to find for beginners. 

Does that need an update? If so where's the documentation source and I'll fix it.

**Comment by cpq** [comment]
Updated, thanks so much.
