### ISSUE TITLE
Load JavaScript Files Dynamically by file name or path

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [cesanta/mongoose-os#455]
I found that Mongoose has option to load file using load('') function call, I would like to understand if mongoose can load files dynamically on need basis from the device storage itself?

```javascript
// static loading file.
load('api_config.js');
```

We are researching into an approach, where we could download a mjs compatible javascript file and save into ESP32 internal storage as code blob/file abstraction. Then load the code blob/saved file into ESP32 using load or low level JS Loader on need basics. I could not find any code reference for same. 

Looking at https://news.ycombinator.com/item?id=13482370, seems like mjs has byte code compilation done before deploying JS into device. But do you have any provision that we can send some JS code either in src format or byte code format, which can be loaded into ESP32 on need basic

**Comment by cpq** [comment]
You can upload files to the ESP32 using `FS.Put` RPC.

The usual way to change the JS logic remotely is to upload JS files, including `init.js`, and then reboot the box. Upon startup, the device executes `init.js` automatically.

The alternative approach would be to implement a simple "JS executor" RPC: you upload a JS file, then trigger the executor RPC to execute it, without reboot.
