### ISSUE TITLE
OTA CC3200 fails with checksum error 

### ISSUE THREAD

**Issue by iliapenev** [cesanta/mongoose-os#459]
OTA CC3200 fails with checksum error. 
Tested with Mongoose 2.6 

```
mgos_updater_progres 31.74% total, spiffs.img 51200 of 98368
verify_checksum spiffs.img.1.0: have b62e278e38556a81b6f243555b095f389a6a48f2, want 1d2ccc4cb5801ede8fa677f2ebb2164113cf3cb0
```
Test application main.c and mos.yml and full log could be found here:

https://gist.github.com/iliapenev/7006cdeabe02eedd6e07469beed0898c

Build and updated with following commands 

`mos build --local --repo mongoose-os --verbose --no-libs-update --libs-dir mos-libs`

`curl -v -F file=@build/fw.zip http://192.168.4.1/update`

I have similar failure with another project, but there fails on `app.bin`

**Comment by rojer** [comment]
so, i actually had a look at this today. yes, it fails with checksum error, but no, hashing seems to be workign correctly - i even wrote an extensive test suite to verify that on all our platform. well, at least we have that.
will have another stab at it later.
