### ISSUE TITLE
GPL clarification

### ISSUE THREAD

**Issue by yagamy4680** [cesanta/mongoose-os#542]
We feel exciting to see programming in javascript on embedded system, but have question about license. Though `Mongoose-OS` is **Apache**, but `mjs` is **GPL**. `Mongoose-OS`, `mjs`, and my app codes are compiled and linked together before deploying to target hardware boards. => Does it indicate `my app codes` shall be also **GPL**?

But, I don't want to open my app codes. Shall I acquire mjs commercial license to solve such conflict?

**Comment by cpq** [comment]
Please email to support@cesanta.com.
Thanks!
