### ISSUE TITLE
mgos_ro_vars.h not found

### ISSUE THREAD

**Issue by GilWu** [cesanta/mongoose-os#543]
Hi,

I saw that in version 2.17.0 mgos_ro_vars.h is included in mgos.h. Visual Studio Code has some problems to find this header file. Indeed, I couln't find it anywhere in the repo, too.

Can you please help?

**Comment by nliviu** [comment]
`mgos_ro_vars.h` is generated by the build process.
You can find it in `build/gen`.

**Comment by rojer** [comment]
yes, this file along with some others are generated by the mos utilioty during build and are stored in the app's build/gen directory.
