### ISSUE TITLE
Fail when calling mgos_ints_enable()

### ISSUE THREAD

**Issue by VaclavVejrosta** [cesanta/mongoose-os#551]
Hi,
this problem occures when I enable interrupts with function `mgos_ints_enable()` . But it never happened with mos version 2.17. It fails only with mos version 2.18. It fails always when this function is called. Please see attached logs:

![image](https://user-images.githubusercontent.com/55979726/92079387-1761a380-edc0-11ea-8d76-39be54c25d37.png)

![image](https://user-images.githubusercontent.com/55979726/92079413-234d6580-edc0-11ea-9eee-1553b7a2604d.png)

**Comment by VaclavVejrosta** [comment]
Problem solved in issue #550

**Comment by rojer** [comment]
looks like it's related to multicore operation.
if you can create a simple app that reproduces it, i can take a look.
