### ISSUE TITLE
C++ undefined references? Not linking like it should do.

### ISSUE THREAD

**Issue by Respawnerhd** [cesanta/mongoose-os#555]
Following errors iam getting:

```
undefined reference to `mg
undefined reference to `mg_mgr_poll'_bind'
undefined reference to `mg_mgr_init'
undefined reference to `mbuf_remove'
```

how do i fix this?
If i execute this: `g++ main.cpp -lmongoose `
it gives me that:
`c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: cannot find -lmongoose`

**Comment by DrBomb** [comment]
Are you doing a local or a remote build? You don't have to execute g++ at any moment to build a mongoose-os app.

Please read the docs [https://mongoose-os.com/docs/mongoose-os/userguide/build.md](https://mongoose-os.com/docs/mongoose-os/userguide/build.md)

**Comment by Respawnerhd** [comment]
> Are you doing a local or a remote build? You don't have to execute g++ at any moment to build a mongoose-os app.
> 
> Please read the docs https://mongoose-os.com/docs/mongoose-os/userguide/build.md

Iam doing it locally on my pc with visual studio code without any docker. 

In theyre docs states that i just need to place the mongoose.c and mongoose.h in my build directory

**Comment by DrBomb** [comment]
Looks like this issue is related to "mongoose" the networking library instead of "mongoose-os" which is the IoT development framework. This is the correct repo to fill the issue [https://github.com/cesanta/mongoose](https://github.com/cesanta/mongoose)
