### ISSUE TITLE
ESP-IDF update for ESP-32 to protect against Braktooth

### ISSUE THREAD

**Issue by adamrhass** [cesanta/mongoose-os#580]
As noted here ([https://asset-group.github.io/disclosures/braktooth/](https://asset-group.github.io/disclosures/braktooth/)), there are security issues that need to be fixed with an ESP-IDF update because of the Braktooth vulnerabilities. Since mongoose sits on top of the ESP-IDF, I assume this update needs to come from mongoose. It looks like the current version is on 4.2r-1 which I believe was released 9 months ago. I am not an expert on this subject. I just want to make sure our devices stay secure. I also noticed this issue by @rojer #565 .

**Comment by rojer** [comment]
updated to the tip of upstream 4.2
