### ISSUE TITLE
Possible race issues?

### ISSUE THREAD

**Issue by ryancaicse** [cesanta/mongoose-os#585]
Hi, the lock `us->lock` seems to guard the variable `us->locked`. However, the lock is released before accessing `us->locked`. Should it be a bug?
https://github.com/cesanta/mongoose-os/blob/1ce60619904403e47c81df88d8622e2614c9588e/src/mgos_uart.c#L42-L50

**Comment by rojer** [comment]
you are right. feel free to send a PR.
