### ISSUE TITLE
Potential resource leaks

### ISSUE THREAD

**Issue by ryancaicse** [cesanta/mongoose-os#590]
Should a `fclose(fp)` be put before return at Line 44?
https://github.com/cesanta/mongoose-os/blob/0be68369e7215791b03632fc133252d3fa04e499/src/common/cs_file.c#L41-L48

**Comment by ryancaicse** [comment]
Could you take a look? Many thanks. @mkmik

**Comment by rojer** [comment]
it's been fixed in https://github.com/cesanta/mongoose-os/commit/018961db7d7df3887c5e1fc51a5686600417e649, by none other than yourself :)
