### ISSUE TITLE
esp32-c3 build fails with `unknown CMake command "add_prebuilt_library"`

### ISSUE THREAD

**Issue by nliviu** [cesanta/mongoose-os#605]
After the latest commit as of 22/02/2023 build for esp32c3 fails
```
CMake Error at /mongoose-os/platforms/esp32xx/esp32xx.cmake:11 (add_prebuilt_library):
  Unknown CMake command "add_prebuilt_library".
```
It looks like `/mongoose-os/platforms/esp32c3/CMakeLists.txt` is missing
```
include($ENV{IDF_PATH}/tools/cmake/project.cmake)
```

**Comment by rojer** [comment]
@a2800276 can you check and put up a fix please?

**Comment by a2800276** [comment]
Ah yes, didn't copy over to esp32c3, sorry. 
Let me try to set up a mini project to build for both plattforms.

**Comment by a2800276** [comment]
Ok, I've copied the CMakeFiles.txt and tested it: https://github.com/cesanta/mongoose-os/pull/606

I'm not sure how you guys typically go about testing the build. I tried building `demojs` app for esp32 and esp32c3 before and after, before esp32 worked and c3 failed, after both build suceeded.

**Comment by nliviu** [comment]
Thank you!

**Comment by a2800276** [comment]
No worries, I should have tested the PR before submitting. Sorry about being the elephant in the china shop in the first place :)
