### ISSUE TITLE
Does this still maintained?

### ISSUE THREAD

**Issue by hitecSmartHome** [cesanta/mongoose-os#614]
### Hi!
I just stumbled upon this firmware.
**Looks really good!**

_I have a couple of questions_

- Does it use ESP IDF under the hood for ESP32 ( with all the bugs in there )?
- Does it use the latest IDF?
- Is there a possibility to use custom libraries written for Arduino or IDF?
- Does it work on any kind of ESP32? ( older Wrover-E or newer S3s )

Thank you very much if you take the time to read and or answer!

**Comment by scaprile** [comment]
This is not an issue.
Please direct your questions to the forum, and please read release notes.
https://github.com/cesanta/mongoose-os#docs-support
https://mongoose-os.com/mos.html
https://github.com/cesanta/mongoose-os/releases/tag/2.20.0
> mongoose-os: ESP32: Update ESP-IDF to 4.2+b132b611

**Comment by hitecSmartHome** [comment]
Thanks.
